import { StyleSheet } from "react-native";

const colors = {
  primary: '#4361ee',
  secondary: '#3f37c9',
  accent: '#4895ef',
  success: '#4cc9f0',
  danger: '#f72585',
  warning: '#f8961e',
  dark: '#212529',
  light: '#f8f9fa',
  white: '#ffffff',
  gray: '#6c757d',
  lightGray: '#dee2e6',
  background: '#f8fafc',
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  content: {
    flex: 1,
    padding: 0,
  },
  profileSection: {
    backgroundColor: colors.white,
    paddingTop: 36,
    paddingBottom: 30,
    alignItems: 'center',
    marginBottom: 20,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    shadowColor: colors.dark,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 5,
  },
  profileImageContainer: {
    position: 'relative',
    marginBottom: 20,
  },
  profileImage: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 4,
    borderColor: colors.white,
    shadowColor: colors.dark,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 8,
  },
  editImageButton: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: colors.primary,
    borderRadius: 18,
    width: 36,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: colors.dark,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 2,
    borderColor: colors.white,
  },
  profileName: {
    fontSize: 24,
    fontWeight: 'bold',
    color: colors.dark,
    marginBottom: 6,
    textAlign: 'center',
  },
  profileEmail: {
    fontSize: 15,
    color: colors.gray,
    marginBottom: 16,
    textAlign: 'center',
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.light,
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 15,
    marginBottom: 24,
  },
  ratingText: {
    fontSize: 15,
    fontWeight: 'bold',
    color: colors.dark,
    marginLeft: 6,
  },
  ratingSubtext: {
    fontSize: 13,
    color: colors.gray,
    marginLeft: 6,
  },
  infoContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
    paddingHorizontal: 16,
    marginTop: 5,
  },
  infoColumn: {
    alignItems: 'center',
    paddingHorizontal: 10,
    width: '33%',
  },
  infoIconContainer: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: colors.light,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
    shadowColor: colors.dark,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  infoLabel: {
    fontSize: 12,
    color: colors.gray,
    marginBottom: 2,
    textAlign: 'center',
  },
  infoValue: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.dark,
    textAlign: 'center',
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.dark,
    marginLeft: 20,
    marginTop: 10,
  },
  menuSection: {
    backgroundColor: colors.white,
    borderRadius: 20,
    padding: 10,
    marginHorizontal: 10,
    marginVertical: 5,
    shadowColor: colors.dark,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 5,
  },
  menuItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 18,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.lightGray,
  },
  menuItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  menuItemIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  menuItemText: {
    fontSize: 16,
    color: colors.dark,
    marginLeft: 16,
    fontWeight: '500',
  },
  destructiveText: {
    color: colors.danger,
  },
});

export default styles;